try:
    print("Тест")
except Exception as e:
    print(f"Ошибка: {e}")
    pass


print("Ошибка при загрузке или отображению контактов:", e)
